# Generated by Django 2.0 on 2017-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('request_path', models.CharField(max_length=255)),
                ('total_visit_count', models.IntegerField()),
                ('today_visit_count', models.IntegerField()),
                ('last_visit_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, max_length=60)),
                ('user_agent', models.CharField(max_length=255)),
                ('referrer', models.CharField(max_length=255)),
                ('total_visit_count', models.IntegerField()),
                ('today_visit_count', models.IntegerField()),
                ('last_visit_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
